### ISSUE TITLE
Does not seams to work under Godot 4 beta 10

### ISSUE THREAD

**Issue by Akira1San** [arcaneenergy/godot-multimesh-scatter#2]
When trying to add a mesh to multimesh nothing show up, but i managed to get this error "ERROR: Condition "instance_count > 0" is true."

**Comment by arcaneenergy** [comment]
Seems to be working fine for me.
I think this is caused when you delete and recreate the multimesh. Don't delete the multimesh, instead use the multimesh that is created automatically when you add the node.
Try recreating the node :)

**Comment by Akira1San** [comment]
Thx, i think the multimesh is bugged with my AMD Radeon.

**Comment by arcaneenergy** [comment]
I've closed this issue. If you have questions or found a bug, you can reopen this or create a new issue.
