### ISSUE TITLE
Doesnt Work (Details Inside) (Solved)

### ISSUE THREAD

**Issue by yalazur** [arcaneenergy/godot-multimesh-scatter#7]
OS: Win 11
Godot Ver: RC 2

Step by Step:
- Load a new project
- download the Plugin from the AssetLib
- enable setting
- add world env
- add mesh instannce
- add multiscatter node
- enable multi scatter
- load box mesh as the scatter object
- nothing happened

**Comment by arcaneenergy** [comment]
Works well for me. Make sure your scene has collisions and also check your collision mask. If you're using a CSG mesh, enable "Use Collision".

![screenshot](https://user-images.githubusercontent.com/52855634/218989929-3f4c64cf-186f-4a55-9591-df8d3a5c18ee.png)

**Comment by yalazur** [comment]
thanks, it worked now, but i ran into another bug(?):

it said the scattering happens automatically, but when i tried to increase instance amount, nothing happened, and when i tried to move the scatter node (in attempt to refresh it), the instance amount resets back to 100

EDIT:
i found a way: so i was changing this one
![image](https://user-images.githubusercontent.com/113665849/219022323-5cc13f47-6b74-4f05-8828-5e90fb567ff0.png)
when i really should changing this one instead
![image](https://user-images.githubusercontent.com/113665849/219022418-c0dfc48f-707d-4ef3-aa6a-3069076bd78f.png)

**Comment by arcaneenergy** [comment]
All good! I'll close this issue since you've solved it. If you find a bug you can open another issue or reopen this one.
