### ISSUE TITLE
Give option for Y-up Normal Vector

### ISSUE THREAD

**Issue by bikemurt** [arcaneenergy/godot-multimesh-scatter#9]
Multimesh instances are defaulted to be the normal of the terrain. Should provide an option (boolean export var) to use Y-up vector instead (0, 1, 0). I have a local change that I can post as a PR when I get the time but wanted to see if this project is still active first

Edit: this is useful for things like trees where they don't grow out of a normal vector to the ground, they basically grow straight up (some random rotation helps, which works fine)

**Comment by arcaneenergy** [comment]
The project is not active, but I can gladly merge your changes if they are beneficial:)
Maybe an option to specify the normal vector instead of a boolean export variable would maybe be better?

**Comment by bikemurt** [comment]
Agreed, that totally makes sense. I dropped in a PR. Thanks for creating this tool, by the way! It's awesome

**Comment by arcaneenergy** [comment]
Thanks 👍
